### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by jwulf** [tvvignesh/prisma-zeebe-bug#2]
git clone
npm i
npm rebuild # rebuild grpc binary for arch
node testing.js

```
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '@generated/photon'
Require stack:
- /Users/sitapati/workspace/Camunda/prisma-zeebe-bug/testing.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/sitapati/workspace/Camunda/prisma-zeebe-bug/testing.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/sitapati/workspace/Camunda/prisma-zeebe-bug/testing.js' ]
}
```

**Comment by tvvignesh** [comment]
@jwulf The `npm install` command is removing the @generated folder from the node_modules folder and hence you are getting the error. If you take a backup of the @generated folder from within node_modules somewhere, do npm installl and then put it back again inside node_modules, it is working. Not sure about the right way of doing this though.

**Comment by tvvignesh** [comment]
Updated README.
